### ISSUE TITLE
cloudformation_diff doesn't work

### ISSUE THREAD

**Issue by Art3mK** [cytopia/ansible-cloudformation#26]
Hey!

Looks like cloudformation_diff script doesn't work anymore. Tried with latest ansible available in python:3-alpine docker image
```
TASK [ansible-role-cloudformation : diff cloudformation template parameters] ***********************************************************************************************************************************************************************************************************************************************
fatal: [infrastructure]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

/root/.ansible/tmp/ansible-tmp-1563169478.9655852-25792851061594/AnsiballZ_cloudformation_diff.py:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1563169478.9655852-25792851061594/AnsiballZ_cloudformation_diff.py", line 114, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1563169478.9655852-25792851061594/AnsiballZ_cloudformation_diff.py", line 106, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1563169478.9655852-25792851061594/AnsiballZ_cloudformation_diff.py", line 49, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/usr/local/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/local/lib/python3.7/imp.py", line 169, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 630, in _exec
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/ansible_cloudformation_diff_payload_35lmcfal/__main__.py", line 590, in <module>
  File "/tmp/ansible_cloudformation_diff_payload_35lmcfal/__main__.py", line 488, in main
AttributeError: 'str' object has no attribute 'decode'



PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************************************************************
infrastructure             : ok=8    changed=0    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0

/src # python -V
Python 3.7.4
/src # pip list | egrep "(boto|cfn)"
boto3           1.9.188
botocore        1.12.188
cfn-flip        1.2.1
/src #
```

**Comment by cytopia** [comment]
This is most likely a Python3 issue. Can you try this with Python2?

**Comment by Art3mK** [comment]
yeah, got it working with python2, thanks!

**Comment by gizmonicus** [comment]
I fixed this issue with the following change. I'm not sure this is the right way to solve it, but it appears to work for all my test cases.

```
diff --git a/library/cloudformation_diff.py b/library/cloudformation_diff.py
index 131ddab2..fea0cbda 100644
--- a/library/cloudformation_diff.py
+++ b/library/cloudformation_diff.py
@@ -484,8 +484,8 @@ def main():
     cloud_tags = to_dict(cloud_data.get('Tags', []), 'Key', 'Value')
 
     # Get local data
-    with open(module.params.get('template'), "rt") as f:
-        local_template = f.read().decode("UTF-8")
+    with open(module.params.get('template'), "rt", encoding='utf8') as f:
+        local_template = f.read()
 
     # Ignore final newline?
     #
```

Edit: Note that this does appear to break Python2 compatability. If you just drop the encoding parameter completely, it seems to work for both, but then I don't know what impact that has on users who aren't using UTF-8 encoding.
